# Funding configuration for p2p-path-finder
#
# This file defines sponsorship/funding platforms displayed on GitHub.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: somework

